name: epilink
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
  - numpy>=1.22
  - scipy>=1.9
  - numba>=0.58,<0.61
  - pip
  - pip:
      # dev tools only; keep in sync with [project.optional-dependencies].dev
      - pytest>=7.3
      - pytest-mock>=3.10
      - pytest-cov>=4.0
      - mypy>=1.4
      - ruff>=0.5
      - black>=24.1
      - pre-commit>=3.3
      - mkdocs>=1.5
      - mkdocs-material>=9.5
      - mkdocstrings[python]>=0.24
      # install local package without dependencies (resolved by conda)
      - -e .
