name: epilink
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy>=2.0
  - scipy>=1.14
  - matplotlib
  - seaborn
  - pytest>=7.3
  - pytest-cov>=4.0
  - mypy>=1.4
  - ruff>=0.5
  - black>=24.1
  - pre-commit>=3.3
  - pip:
      - -e .
