site_name: epilink
theme:
  name: material
nav:
  - Home: index.md
  - Usage: usage.md
  - API: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
docs_dir: docs
