"""Build the static teaching dataset for the EpiLink explorer.

The resulting JSON contains no user data and is the only model-data dependency
of the published site. Every distribution, CDF, and compatibility grid is
generated by the local ``epilink`` Python package.

Run from the repository root:
    conda run -n PhD python web/build_data.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

from epilink import EpiLink, InfectiousnessToTransmission, NaturalHistoryParameters

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "web" / "data" / "epilink-explorer-data.json"
MC_SAMPLES = 50_000
MAXIMUM_DEPTH = 5
INTEGRATION_GRID_POINTS = 256
SAMPLING_GRID_POINTS = 256
TIME_VALUES = np.arange(-15.0, 35.0 + 0.01, 0.5)
GENETIC_VALUES = np.arange(12.0, -0.01, -1.0)

PARAMETER_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "key": "incubation_shape",
        "label": "Incubation shape",
        "group": "Natural history",
        "unit": "",
        "values": (3.5, 4.5, 5.807, 7.5, 10.0),
        "default_index": 2,
        "description": "Changes the shape of the infection-to-symptom distribution while the incubation scale remains at its baseline.",
    },
    {
        "key": "incubation_scale",
        "label": "Incubation scale",
        "group": "Natural history",
        "unit": "days",
        "values": (0.5, 0.7, 0.948, 1.2, 1.6),
        "default_index": 2,
        "description": "Stretches or contracts the E and P stage durations together, shifting expected timing and branch lengths.",
    },
    {
        "key": "latent_shape",
        "label": "Latent-stage shape",
        "group": "Natural history",
        "unit": "",
        "values": (0.75, 2.0, 3.38, 4.5, 5.5),
        "default_index": 2,
        "description": "Redistributes the incubation period between the non-infectious latent stage and the presymptomatic infectious stage.",
    },
    {
        "key": "symptomatic_rate",
        "label": "Symptomatic removal rate",
        "group": "Natural history",
        "unit": "per day",
        "values": (0.18, 0.28, 0.37, 0.5, 0.75),
        "default_index": 2,
        "description": "Higher values shorten the expected symptomatic infectious period.",
    },
    {
        "key": "symptomatic_shape",
        "label": "Symptomatic-stage shape",
        "group": "Natural history",
        "unit": "",
        "values": (0.5, 0.75, 1.0, 1.5, 2.5),
        "default_index": 2,
        "description": "Changes the dispersion of time spent in the symptomatic infectious stage while retaining the removal-rate parameterisation.",
    },
    {
        "key": "transmission_rate_ratio",
        "label": "Presymptomatic transmission level",
        "group": "Natural history",
        "unit": "relative to symptomatic transmission",
        "values": (0.5, 1.2, 2.29, 4.0, 6.0),
        "default_index": 2,
        "description": "Sets how much more or less infectious the presymptomatic stage is than the symptomatic stage.",
    },
    {
        "key": "testing_delay_shape",
        "label": "Testing-delay shape",
        "group": "Testing",
        "unit": "",
        "values": (0.5, 1.0, 2.0, 3.5, 5.0),
        "default_index": 2,
        "description": "Changes the shape and spread of the onset-to-testing delay distribution.",
    },
    {
        "key": "testing_delay_scale",
        "label": "Testing-delay scale",
        "group": "Testing",
        "unit": "days",
        "values": (0.25, 0.5, 1.0, 1.75, 3.0),
        "default_index": 2,
        "description": "Scales the time from symptom onset to sampling, changing the surveillance contribution to observed timing.",
    },
    {
        "key": "substitution_rate",
        "label": "Median substitution rate",
        "group": "Clock",
        "unit": "substitutions per site per year",
        "values": (0.00025, 0.0005, 0.001, 0.0015, 0.002),
        "default_index": 2,
        "description": "Changes the median molecular-clock rate used to convert a transmission branch length into expected consensus differences.",
    },
    {
        "key": "relaxation",
        "label": "Relaxed-clock variation",
        "group": "Clock",
        "unit": "",
        "values": (0.0, 0.15, 0.33, 0.55, 0.8),
        "default_index": 2,
        "description": "Controls how much branch-specific clock rates vary around the median; zero is a strict clock.",
    },
    {
        "key": "genome_length",
        "label": "Genome length",
        "group": "Clock",
        "unit": "sites",
        "values": (15000, 24000, 29903, 36000, 50000),
        "default_index": 2,
        "description": "Scales a per-site substitution rate to the expected number of substitutions across the genome.",
    },
)


def main() -> None:
    base_parameters = NaturalHistoryParameters().to_dict()
    models: dict[str, dict[str, dict[str, Any]]] = {}
    target_labels: tuple[str, ...] | None = None
    configurations = [("baseline", base_parameters)]
    for definition in PARAMETER_CATALOG:
        for index, value in enumerate(definition["values"]):
            if index == definition["default_index"]:
                continue
            varied = dict(base_parameters)
            varied[definition["key"]] = value
            configurations.append((f"{definition['key']}:{index}", varied))

    for configuration_key, parameter_values in configurations:
        print(f"Generating {configuration_key}", flush=True)
        configuration_target_labels, models[configuration_key] = generate_configuration(
            parameter_values
        )
        if target_labels is None:
            target_labels = configuration_target_labels
        elif configuration_target_labels != target_labels:
            raise RuntimeError("Generated models expose different scenario sets.")

    if target_labels is None:
        raise RuntimeError("No model configurations were generated.")

    payload = {
        "format_version": 1,
        "build": {
            "generator": "web/build_data.py",
            "mc_samples": MC_SAMPLES,
            "maximum_depth": MAXIMUM_DEPTH,
            "profile_integration_grid_points": INTEGRATION_GRID_POINTS,
            "profile_sampling_grid_points": SAMPLING_GRID_POINTS,
            "rng_seed": 2026,
            "sensitivity_design": "one_parameter_at_a_time",
        },
        "baseline_parameters": base_parameters,
        "parameter_catalog": PARAMETER_CATALOG,
        "target_labels": target_labels,
        "surface": {
            "time_values": rounded(TIME_VALUES),
            "genetic_values": rounded(GENETIC_VALUES),
        },
        "models": models,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(payload, separators=(",", ":")), encoding="utf-8")
    print(
        f"Wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)} ({OUTPUT_PATH.stat().st_size / 1_000_000:.1f} MB)"
    )


def generate_configuration(
    parameter_values: dict[str, Any],
) -> tuple[tuple[str, ...], dict[str, Any]]:
    parameters = NaturalHistoryParameters(**parameter_values)
    deterministic_model = build_model(parameters, "deterministic")
    stochastic_model = build_model(parameters, "stochastic")
    target_labels = tuple(scenario.label() for scenario in deterministic_model.scenarios)
    if tuple(scenario.label() for scenario in stochastic_model.scenarios) != target_labels:
        raise RuntimeError("Deterministic and stochastic models expose different scenario sets.")
    scenario_distributions = {
        label: {
            "time": distribution_summary(draws["time_draws"], discrete=True),
            "branch": distribution_summary(
                draws["branch_draws"], lower_bound=0.0, include_ecdf=False
            ),
            "genetic": {
                "deterministic": distribution_summary(
                    deterministic_model.draws_by_scenario[label]["genetic_draws"],
                    lower_bound=0.0,
                    discrete=True,
                ),
                "stochastic": distribution_summary(
                    stochastic_model.draws_by_scenario[label]["genetic_draws"],
                    lower_bound=0.0,
                    discrete=True,
                ),
            },
        }
        for label, draws in deterministic_model.draws_by_scenario.items()
    }
    surface_scores = {
        mutation_process: {
            label: rounded(
                np.asarray(
                    model.score_target(
                        TIME_VALUES[None, :],
                        GENETIC_VALUES[:, None],
                        target=label,
                    ),
                    dtype=float,
                )
            )
            for label in target_labels
        }
        for mutation_process, model in (
            ("deterministic", deterministic_model),
            ("stochastic", stochastic_model),
        )
    }
    return target_labels, {
        "scenario_distributions": scenario_distributions,
        "surface_scores": surface_scores,
        "derived": {
            "presymptomatic_shape": round(parameters.presymptomatic_shape, 4),
            "incubation_mean": round(
                parameters.incubation_shape * parameters.incubation_scale,
                4,
            ),
            "symptomatic_mean": round(1.0 / parameters.symptomatic_rate, 4),
            "testing_delay_mean": round(
                parameters.testing_delay_shape * parameters.testing_delay_scale,
                4,
            ),
            "presymptomatic_transmission_fraction": round(
                parameters.presymptomatic_transmission_fraction,
                4,
            ),
            "daily_clock_rate": round(
                (parameters.substitution_rate * parameters.genome_length) / 365.0,
                6,
            ),
        },
    }


def build_model(parameters: NaturalHistoryParameters, mutation_process: str) -> EpiLink:
    profile = InfectiousnessToTransmission(
        parameters=parameters,
        rng_seed=2026,
        integration_grid_points=INTEGRATION_GRID_POINTS,
        sampling_grid_points=SAMPLING_GRID_POINTS,
    )
    return EpiLink(
        transmission_profile=profile,
        maximum_depth=MAXIMUM_DEPTH,
        mc_samples=MC_SAMPLES,
        target="ad(0)",
        mutation_process=mutation_process,
    )


def distribution_summary(
    values: np.ndarray,
    lower_bound: float | None = None,
    include_ecdf: bool = True,
    discrete: bool = False,
) -> dict[str, Any]:
    array = np.asarray(values, dtype=float)
    lower, upper = np.quantile(array, [0.01, 0.99])
    if discrete:
        array = np.rint(array)
        padding = max(1, int(np.ceil((upper - lower) * 0.12)))
        lower = int(np.floor(lower)) - padding
        upper = int(np.ceil(upper)) + padding
        if lower_bound is not None:
            lower = max(int(np.ceil(lower_bound)), lower)
        edges = np.arange(lower - 0.5, upper + 1.5)
        counts, _ = np.histogram(np.clip(array, lower, upper), bins=edges)
    else:
        padding = max(0.5, (upper - lower) * 0.12)
        lower = lower - padding
        if lower_bound is not None:
            lower = max(lower_bound, lower)
        upper = upper + padding
        edges = np.linspace(lower, upper, 41)
        counts, _ = np.histogram(np.clip(array, lower, upper), bins=edges)
    sorted_values = np.sort(array)
    summary: dict[str, Any] = {
        "histogram": {"edges": rounded(edges), "counts": counts.astype(int).tolist()},
    }
    if include_ecdf:
        indices = np.unique(np.round(np.linspace(0, sorted_values.size - 1, 101)).astype(int))
        summary["ecdf"] = {
            "values": rounded(sorted_values[indices]),
            "probabilities": rounded((indices + 1) / sorted_values.size),
        }
    return summary


def rounded(values: np.ndarray) -> list[Any]:
    return np.asarray(values, dtype=float).round(4).tolist()


if __name__ == "__main__":
    main()
